name: fitto
description: AI-powered fashion styling + local shops ordering app.
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  firebase_analytics: ^11.0.0
  flutter_riverpod: ^2.6.1

  firebase_core: ^3.15.2
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^17.2.4
  google_sign_in: ^6.2.1
  change_app_package_name: ^1.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
